use std::process::Command;

fn main() {
    // check out latest generated bytecode
    let _code = Command::new("git")
                       .arg("restore")
                       .arg("--source")
                       .arg("origin/BYTECODE")
                       .arg("--")
                       .arg("src/gen/code.rs")
                       .output();
}
