use std::process::Command;

fn main() {
    // check out latest generated bytecode
    let _code = Command::new("git")
                       .arg("checkout")
                       .arg("c1201d206db71ea35bca6ecce410d5903181fbcc")
                       .arg("src/gen/code.rs")
                       .output();
}
