use std::process::Command;

fn main() {
    // check out latest generated bytecode
    let _code = Command::new("git")
                       .arg("checkout")
                       .arg("d6668ec00ed9a9be5fa1151477ee467f8ef3e18f")
                       .arg("src/gen/code.rs")
                       .output();
}
